### ISSUE TITLE
Missed breaking change in kustomize-controller

### ISSUE THREAD

**Issue by h3mmy** [h3mmy/bloopySphere#619]
# Details

**What steps did you take and what happened:**

Read release notes and merged #618 before checking known issues. Flux is now failing to reconcile a couple of resources. Here is the related issue

https://github.com/fluxcd/flux2/issues/1522#issuecomment-1103847223

**What did you expect to happen:**

Smoothness

**Anything else you would like to add:**

**Additional Information:**

**Comment by h3mmy** [comment]
Will utilize https://github.com/kubernetes-sigs/kustomize/pull/4453 strategy which should be included with https://github.com/fluxcd/flux2/releases/tag/v0.29.1

**Comment by hiddeco** [comment]
Heads up that the change to `git::` is not strictly required, it works fine with `v0.29.1` as also confirmed in tests now: https://github.com/fluxcd/kustomize-controller/blob/v0.24.1/controllers/testdata/remote/kustomization.yaml#L7

**Comment by h3mmy** [comment]
Thanks! I wasn't sure about that but I can confirm `git::` is indeed not required.
